version: '3'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=azer
      - MONGO_INITDB_ROOT_PASSWORD=azer

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=azer
      - ME_CONFIG_MONGODB_ADMINPASSWORD=azer
      - ME_CONFIG_MONGODB_SERVER=mongo
    ports:
      - "8081:8081"
    depends_on:
      - mongo
  nest-app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: nest-app
    image: azer/nest-app:${IMAGE_TAG}
    ports:
      - "3000:3000"
    environment:
      - DB_URL=mongodb://azer:azer@mongo:27017
    depends_on:
      - mongo